apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: rest-service-db
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: rest-service-db
    apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: api_descriptor
      value:
        type: openapi
        location: 
          path: "/api-docs"
        owner: default-team
        system: java-rest
        description: Tanzu-java-rest-service
    - name: gitops_repository
      value: ssh://git@github.com:jricho/tap-gitops.git
    - name: gitops_branch
      value: rest-service-db
  source:
    git:
      url: https://github.com/jricho/application-accelerator-samples
      ref:
        branch: main
    subPath: java-rest-service
  serviceClaims:
    - name: database
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: customer-database
